version: "1"
services:
  coin-service:
    container_name: coin-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 1010:1010

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090